dict = {
    "Dean.computing@sathyabama.ac.in": ruh6hwrdq9oucn0cxzwh
lakshmanan.cse@sathyabama.ac.in	rzv9dnvi0arq3jlrbxw6
vigneshwari.cse@sathyabama.ac.in	gg8rmjjw3xrfrz9k6sky
murugan.cse@sathyabama.ac.in	nnwi6wnglctnduakdoyx
bharathi.cse@sathyabama.ac.in	tm2ek6vzzir1r0avgpca
aroul.cse@sathyabama.ac.in	ws9uxos2lcvuhzgu1eaq
albert.cse@sathyabama.ac.in	non72znxcivzkofxzjvx
ankayarkanni.cse@sathyabama.ac.in	yqdlrelfiojbtrhvgbo7
maryposonia.cse@sathyabama.ac.in	s6k6g2x2c6bwydlw8sy7
pravin.cse@sathyabama.ac.in	zve8fovwn95t8xlu15ke
kamalesh.cse@sathyabama.ac.in	rpi2eoztgyw9eph3r701
princemary.cse@sathyabama.ac.in	p6tcj0tmjdifmx3kjw04
vijiamuthamary.cse@sathyabama.ac.in	lssc9mcvldtglyqofm4l
premjacob.cse@sathyabama.ac.in	uutj2ajfmmqwsjkvenjf
sathyabamar.cse@sathyabama.ac.in	rlccqgnkzqkgbai3magl
usha.cse@sathyabama.ac.in	fxe6h0wig57lerqehbz3
saravanan.cse@sathyabama.ac.in	jpp3sd8f5bc6cns7ykjn
joshilagrace.cse@sathyabama.ac.in	scufpjqghdtjp7ezceyu
asha.cse@sathyabama.ac.in	rjsu5e3exgrlolyh3ijd
mohanaprasad1983@gmail.com	j1r6g3aejt1ote8vo6hl
ashokkumar.cse@sathyabama.ac.in	lxtw6h5gmud0bdfuqwyd
ulagamuthalvi.cse@sathyabama.ac.in	kso4dnq8vwygqusmnipn
praylashyry.cse@sathyabama.ac.in	otjezzaduupltsay1gwt
psmaran@sathyabama.ac.in	a8be8msdfnwbrkurhih1
gnagarajan.cse@sathyabama.ac.in	jdhdqtl6goasz4gd8elg
dhamodaran.cse@sathyabama.ac.in	djvaggg9dvcgwpy8nhqg
janyshabu.cse@sathyabama.ac.in	dwqkcsmbbun7jj3owtk0
srinivasan.cse@sathyabama.ac.in	agxaxsvdxkyqaqh7hton
mercypaulselvan.cse@sathyabama.ac.in	ipwc1b57h0pfjkmrvhtj
sethuraman.cse@sathyabama.ac.in	ddzltedqfhl8znerxhc4
refonna.cse@sathyabama.ac.in	rlvwqxoqrqdxppcvoyxx
yovanfelix@sathyabama.ac.in	pnbdzcssvrkv6ijezawj
meeragandhi.cse@sathyabama.ac.in	eqeu9mw82t1ygqktng3c
christy.cse@sathyabama.ac.in	gbxdqkt4azxhezql5lzc
ramyagfranklin.cse@sathyabama.ac.in	nctgf1pqnmd0rnfh2phm
antopraveena.cse@sathyabama.ac.in	md5r02irhkumc9jliqrh
sujihelen.cse@sathyabama.ac.in	nhkvuhryjxgaugy9hcx4
santhasheela.cse@sathyabama.ac.in	na0nywv1ylv075dnmex2
jancy.cse@sathyabama.ac.in	feq46qlgel6dm3rxoj2i
vignesh.cse@sathyabama.ac.in	kmjgbeilabjhk36qbq0b
suja.cse@gmail.com	doijgbhhznmtemgwivd9
anandhitamil2908@gmail.com	gdkzrdmagk51x1vzek1s
roobini.cse@sathyabama.ac.in	qc9wthnvnbigkumyqmm4
judgi.cse@sathyabama.ac.in	brhx4pntyweek5kf6pjn
yogitha.cse@sathyabama.ac.in	ignnfraicaq5lprhsw4p
maheswari.cse@sathyabama.ac.in	zbelpvyufhsyfrtdt6ui
aishwarya.cse@sathyabama.ac.in	n6wqewko1p3yuelsy8js
deepa.cse@sathyabama.ac.in	cwlqgashw9yxyvu1zar0
kalaiarasi.cse@sathyabama.ac.in	a468df36nkvv5vrlzd1j
selvi.cse@sathyabama.ac.in	gsbwuuqbw7jdahihnqxa
veena.cse@sathyabama.ac.in	pnvjaarxxj9kuo6fzl9f
cruzantony.cse@sathyabama.ac.in	t5pmknwbtskdyidaijza
sridevi.cse@sathyabama.ac.in	qoelct343oslu4o6xh9a
amandeepsingh.cse@sathyabama.ac.in	wrgc2v3aiqnkubsy8nvq
malinideepika.cse@sathyabama.ac.in	slighar9r1uplrtwat8c
Drhemalatha.cse@sathyabama.ac.in	hwm0qdn18lebm6mzsqvq
jayanthi.cse@sathyabama.ac.in	ah4fji7o7e0j1zh0sh2f
srividhya.cse@sathyabama.ac.in	w5si1o72gjde3rdeviqo
babu.cse@sathyabama.ac.in	w3knsocgea96hnllkboh
srividhyasr.cse@sathyabama.ac.in	ekhfhktqm2dhsuyq3ocf
kavitha.cse@sathyabama.ac.in	d4de2ygcfg4raozla4pc
anubarathi.cse@sathyabama.ac.in	ladz5abm1i5dpj2yodx4
rajalakshmi.cse@sathyabama.ac.in	ilpl6ywbmxwmiheue834
ushans.cse@sathyabama.ac.in	funqbxaznwtvtngwq4wt
karthika.cse@sathyabama.ac.in	rlhxxeaupjcaveptii02
vanathi.cse@sathyabama.ac.in	kjg2qd2p9ymgaakkmqga
sandhiya.cse@sathyabama.ac.in	jo1mdjzvkjmfj2lamlwy
karpuradheepan.cse@sathyabama.ac.in	zigtlkdrci0dfq7ee0zx
rajashree.cse@sathyabama.ac.in	qu6szva5rleu9z4qfxgx
jemshia.cse@sathyabama.ac.in	rwnk0m4udjbs7s5wo3af
sankari.cse@sathyabama.ac.in	oj8u4jvnisljnphd1dsz
venkatbabu.cse@sathyabama.ac.in	mt2dvxrinp7djv6ob2jd
murali.cse@sathyabama.ac.in	fcgvthqunedemlhtx97c
nafeesmuneera.cse@sathyabama.ac.in	fvgptxmahu1lcmd3ly22
nancynoella.cse@sathyabama.ac.in	ylvoaibfeqhoveilc3dz
lavanya.cse@sathyabama.ac.in	cnp9a1fjca0vmb2r5sdu
lakshmipriyas.cse@sathyabama.ac.in	nu9jufaerei64tp7kyti
sangeetha.cse@sathyabama.ac.in	b7frnbz4o45yp6gflfhs
devipriya.cse@sathyabama.ac.in	jz618kdcm3usfrdojvde
gowrimanohari.cse@sathyabama.ac.in	eflzm90jlz4supf3p4pk
doni.cse@sathyabama.ac.in	nm6kbhfcyxqb599b740w
daphine.cse@sathyabama.ac.in	gtqcvdtqsltvvwa6fym2
nithya.cse@sathyabama.ac.in	xywokigfe0vocuzr924t
rajasekar.cse@sathyabama.ac.in	u6ogxxmcusgdxkpfsu0p
jeslin.cse@sathyabama.ac.in	zguzhmizvpv7y7qyyafe
ajantha.cse@sathyabama.ac.in	nmuquvl7ntcwuwtfoj7z
mathumitha.cse@sathyabama.ac.in	lqbppz0lpvuyoe8dcvw7
sreekrishna.cse@sathyabama.ac.in	eduwdmkv5czemikbjdoz
priyanka.cse@sathyabama.ac.in	oln7yw4uc7bof5ftdcqv
panimalar.cse@sathyabama.ac.in	eiat5exbz7xftgrtoaxg
devi.cse@sathyabama.ac.in	ip8yknn05p7h9wnujkta
annymick@gmail.com	hjetytre2rlbe9tbe77k
ancymichael.cse@sathyabama.ac.in	esza4pps4yun9iaudhmh
kalaivani.cse@sathyabama.ac.in	nrg08mfc9u2nuzv1faaf
pothumani.cse@sathyabama.ac.in	btne1hza7v9mfcuj6dvz
supriya.cse@sathyabama.ac.in	mnunmmxjmmifq85ksowm
santhiya.cse@sathyabama.ac.in	wzorb3dbqdmsfkcfdnwu
subathra.cse@sathyabama.ac.in	kjsifyvey6a15iwt5vod
nancykirupanithi.cse@sathyabama.ac.in	efquumdekyij3q3cauvi
velvizhi.cse@sathyabama.ac.in	dcwdj1kjw5iuren4f3oo
manjunair.cse@sathyabama.ac.in	aylkaw0m5jznatsx70st
gracelinsheena.cse@sathyabama.ac.in	qllakwdp27cqggkfey3w
jeeva0407@gmail.com	mxoupvpwrxqanfxosrvj
aishwaryad.cse@sathyabama.ac.in	rfzofbr4rix3k5a00suk
niveditha.cse@sathyabama.ac.in	t2tl7evfodm09qogzaro
gopika.cse@sathyabama.ac.in	l7ibrmzuzu3c2pbu414o
mariajones.cse@sathyabama.ac.in	mn30i3fxoogg3atx2voc
saranya.cse@sathyabama.ac.in	qpqtuwxwuemy5i6jxf6y
subapriya.cse@sathyabama.ac.in	dewjuowsmikj0ggigrzw
menaka.cse@sathyabama.ac.in	rdmy53stgwtkhh7kppmf
ashajudi.cse@sathyabama.ac.in	cjkry3wtak2vnbn2jftp
lalitha.cse@sathyabama.ac.in	ukhks7k3rnpzxh0culhf
gkavitha.cse@sathyabama.ac.in	gdh3arrwitbyjmv0h5jl
gowri.cse@sathyabama.ac.in	ufy3hmamidb3dn7espvi
parveenakhther.cse@sathyabama.ac.in	fjxh67wlvgul20fsused
adeepa.cse@sathyabama.ac.in	dryl5citgwcfzskbckpr
vaishnnave.cse@sathyabma.ac.in	k3chdoioslwjvj8plcy1
dhanalakshmi.cse@sathyabama.ac.in	vrkmeydmltayxedsunzh

}