# Generated by Django 4.2 on 2023-07-28 17:39

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_alter_guide_myimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='domain_1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='guide',
            name='myImage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
