# Generated by Django 4.2 on 2023-08-06 10:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_alter_guide_designation_alter_guide_domain_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='designation',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guide',
            name='domain_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='guide',
            name='myImage',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
