# Generated by Django 4.2 on 2024-01-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_alter_guide_designation_alter_guide_domain_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_team',
            name='project_description',
            field=models.CharField(),
        ),
    ]
