# Generated by Django 4.2 on 2024-01-05 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_alter_temp_team_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp_team',
            name='project_description',
            field=models.TextField(),
        ),
    ]
