# Generated by Django 4.2 on 2024-01-22 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0013_alter_temp_team_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='student_1_marks',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='team',
            name='student_2_marks',
            field=models.IntegerField(default=15),
        ),
    ]
