# Generated by Django 4.2 on 2024-01-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_team_student_1_marks_team_student_2_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='student_1_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='team',
            name='student_2_marks',
            field=models.IntegerField(default=0),
        ),
    ]
