# Generated by Django 4.2 on 2024-01-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_remove_team_student_1_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='student_1_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='student_2_marks',
            field=models.IntegerField(default=0),
        ),
    ]
